### ISSUE TITLE
Issue on auth

### ISSUE THREAD

**Issue by dimalusa** [seratch/bigquery4s#5]
Hi,

I've done the readme but it doesn't work.

WHEN I TRY THE AUTH :
`val bq = BigQuery() // expects $HOME/.bigquery/client_secret.json`

I've got this stacktrace :

```
java.lang.IllegalArgumentException
	at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:111)
	at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:37)
	at com.google.api.client.googleapis.auth.oauth2.GoogleClientSecrets.getDetails(GoogleClientSecrets.java:82)
	at com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeFlow$Builder.<init>(GoogleAuthorizationCodeFlow.java:195)
	at bigquery4s.BigQuery$.fromClientSecretJson(BigQuery.scala:120)
	at bigquery4s.BigQuery$.apply(BigQuery.scala:102)
```

It seem's that we never setInstalled or setWeb because web and installed are null.

But in debug mode, client_id / ... are well initialized in clientSecrets.
Can you give me some support ?

Best regards,

**Comment by dimalusa** [comment]
My json is not with the same format as in : 
https://developers.google.com/api-client-library/python/guide/aaa_client_secrets

I've got a flat structure : 
```
{
  "type": "service_account",
  "project_id": "mytest-152614",
...
}
```

**Comment by nykolaslima** [comment]
I've the same issue here. Any solution on this?

**Comment by vijaykramesh** [comment]
with my service account json file, this works:

```scala
val credStream = new FileInputStream(new File("/path/to/service_account.json"))
val scopes = Seq(BigqueryScopes.BIGQUERY, BigqueryScopes.BIGQUERY_INSERTDATA).asJava
val credential = GoogleCredential.fromStream(credStream).createScoped(scopes)
val bq = BigQuery(new NetHttpTransport, new JacksonFactory, credential)
```

I may clean that up and submit a PR so `BigQuery.fromServiceAccount` would work (or add a `BigQuery.fromServiceAccountJson`)
